
let Nave = new Player(275,780,50,50,"imagens/nave.png")
let back = new Player(0,0,650,1156,'imagens/background.jpg')
let inimigo1 = new Player(0,0,100,100,'imagens/inimigo1.png')
let inimigo2 = new Player(295,0,20,100,'imagens/inimigo2.png')
let inimigo3 = new Player(400,0,100,100,'imagens/inimigo3.png')
function jogo(){
    back.desenhar() 
    Nave.desenhar()
    inimigo1.desenhar()
    inimigo2.desenhar()
    inimigo3.desenhar()
    inimigo1.cair()
    inimigo2.cair()
    inimigo3.cair()
    inimigo1.colidir(Nave)
    inimigo2.colidir(Nave)
    inimigo3.colidir(Nave)
    inimigo1.voltar()
    inimigo2.voltar()
    inimigo3.voltar()
    anima = requestAnimationFrame(jogo)
}
jogo()